export default {
  id: 'clinic-pawsitive',
  slug: 'pawsitive-vet-care',
  name: 'Pawsitive Vet Care',
  locale: 'en-PH',
  timezone: 'Asia/Manila',
  currency: 'PHP',
  phone: '+63 917 555 0188',
  email: 'hello@pawsitivevet.example',
  address: 'Quezon City, Metro Manila',
  language: 'taglish',
  access: {
    bookingTitle: 'Mag-book ng visit',
    chatTitle: 'Clinic chat',
    help: 'Ilagay ang demo access code mula sa clinic team para magpatuloy.',
    label: 'Demo access code',
    bookingAction: 'Magpatuloy',
    chatAction: 'Magpatuloy',
    error: 'Hindi ma-access ang demo. Suriin ang code at subukan ulit.',
    staffTitle: 'Staff dashboard',
    staffHelp: 'Ilagay ang staff access code para makita ang live clinic desk.',
    staffLabel: 'Staff access code',
    staffAction: 'Buksan ang dashboard',
    staffError: 'Hindi ma-access ang staff dashboard. Suriin ang code at subukan ulit.'
  },
  booking: {
    kicker: 'Online appointment',
    headline: 'Alaga mo, alaga namin.',
    intro: 'Piliin ang serbisyo at oras na bagay sa inyong schedule. Confirmed ang slot bago kayo pumunta.',
    accessLabel: 'Demo access code',
    accessHelp: 'Ilagay ang code mula sa clinic team para makita ang live na schedule.',
    accessAction: 'Continue',
    serviceHeading: 'Para saan ang visit?',
    serviceHelp: 'Piliin ang service para makita ang available na oras.',
    dateLabel: 'Piliin ang date',
    slotsHeading: 'Available na oras',
    slotsHelp: 'Live ang availability. Ang napiling oras ay ihahanda para sa inyong booking.',
    detailsHeading: 'Ilang detalye lang',
    ownerName: 'Pangalan ninyo',
    mobile: 'Mobile number',
    email: 'Email address (optional)',
    petName: 'Pangalan ng alaga',
    species: 'Uri ng alaga',
    speciesOptions: { dog: 'Aso', cat: 'Pusa', other: 'Iba pa' },
    breed: 'Breed (optional)',
    bookAction: 'I-confirm ang appointment',
    booking: 'Sine-save ang appointment...',
    bookedHeading: 'Booked na ang visit ninyo.',
    bookedBody: 'May reservation na kayo. Makakatanggap kayo ng confirmation at reminder bago ang visit.',
    anotherAction: 'Mag-book ulit',
    unavailable: 'May nag-book na ng oras na iyon. Pumili ng ibang available na slot.',
    slotsEmpty: 'Wala pang available na oras sa date na ito. Subukan ang ibang date.',
    loading: 'Kinukuha ang live na schedule...',
    timeZoneNote: 'Lahat ng oras ay clinic time.',
    required: 'Pakikumpleto ang required fields.',
    accessError: 'Hindi ma-access ang demo. Suriin ang code at subukan ulit.'
  },
  reminders: {
    confirm: {
      subject: 'Paki-confirm ang appointment ni {pet}',
      message: 'Hi {owner}! May {service} si {pet} sa {clinic} sa {appointmentTime}. Confirm: {confirmUrl} Reschedule: {rescheduleUrl}'
    },
    appointment_24h: {
      subject: 'Reminder: appointment ni {pet} bukas',
      message: 'Hi {owner}! Reminder lang: may {service} si {pet} sa {clinic} bukas, {appointmentTime}. Confirm: {confirmUrl} Reschedule: {rescheduleUrl}'
    },
    appointment_2h: {
      subject: 'Appointment ni {pet} in 2 hours',
      message: 'Hi {owner}! 2 hours na lang bago ang {service} ni {pet} sa {clinic}, {appointmentTime}. Confirm: {confirmUrl} Reschedule: {rescheduleUrl}'
    },
    vaccine_due: {
      subject: 'Vaccine reminder para kay {pet}',
      message: 'Hi {owner}! Due na ang {vaccine} vaccine ni {pet}. Mag-book sa {clinic}: {bookingUrl}'
    },
    no_show: {
      subject: 'Missed visit ni {pet}',
      message: 'Hi {owner}! Mukhang na-miss ang visit ni {pet}. Mag-reschedule sa {clinic}: {rescheduleUrl}'
    },
    ownerActions: {
      confirmTitle: 'I-confirm ang appointment',
      rescheduleTitle: 'I-reschedule ang appointment',
      confirmPrompt: 'Pindutin ang continue para i-confirm ang appointment mo.',
      reschedulePrompt: 'Pindutin ang continue para markahan ang appointment para sa rescheduling.',
      continueAction: 'Continue',
      confirmed: 'Confirmed na ang appointment mo.',
      alreadyConfirmed: 'Confirmed na ang appointment mo.',
      rescheduled: 'Nareschedule na ang appointment mo. Makipag-ugnayan sa clinic para pumili ng bagong oras.',
      unavailable: 'Hindi na available ang link na ito.'
    }
  },
  reviews: {
    delayHours: 2,
    googleReviewUrl: 'https://www.google.com/search?q=Pawsitive+Vet+Care+Quezon+City',
    request: {
      subject: 'Kamusta ang visit ni {pet}?',
      message: 'Hi {owner}! Salamat sa pagbisita sa {clinic}. Kumusta si {pet}? I-rate ang experience ninyo dito: {reviewUrl}'
    },
    gate: {
      kicker: 'Clinic feedback',
      title: 'Kamusta ang visit ni {pet}?',
      intro: 'Mahalaga sa amin ang feedback ninyo.',
      prompt: 'Ilang stars ang ibibigay ninyo?',
      starLabel: '{rating} stars',
      feedbackTitle: 'Sabihin sa amin kung paano kami makakabuti.',
      feedbackLabel: 'Private feedback',
      feedbackAction: 'I-send ang feedback',
      submitting: 'Sine-save ang feedback...',
      thanksTitle: 'Salamat sa feedback ninyo.',
      thanks: 'Naipadala na ito sa clinic team.',
      unavailable: 'Hindi na available ang review link na ito.',
      ratingError: 'Hindi ma-save ang rating. Subukan ulit.',
      feedbackError: 'Hindi ma-save ang feedback. Subukan ulit.',
      required: 'Pakilagay ang feedback ninyo.'
    }
  },
  faqs: [
    { question: 'What are your hours?', answer: 'Open kami Monday to Friday, 9 AM to 5 PM, at Saturday, 9 AM to 1 PM.' },
    { question: 'Where are you located?', answer: 'Nasa Quezon City, Metro Manila kami.' },
    { question: 'Do you accept walk-ins?', answer: 'Mas mabilis ang service kapag may appointment. Maaari kang mag-book dito para makapili ng oras.' }
  ],
  chat: {
    title: 'Ask the vet team',
    intro: 'Magtanong tungkol sa clinic o mag-book ng appointment dito.',
    greeting: 'Hi! Ako ang virtual receptionist ng {clinic}. Puwede akong sumagot sa questions at tumulong mag-book ng visit para sa alaga mo.',
    inputLabel: 'Message for the clinic',
    inputPlaceholder: 'Halimbawa: May slot ba bukas para sa anti-rabies?',
    sendAction: 'Send',
    accessError: 'Hindi ma-access ang chat. Suriin ang demo code.',
    unavailable: 'Hindi available ang chat ngayon. Subukan ulit mamaya.'
  },
  dashboard: {
    title: 'Clinic desk',
    intro: 'Live na view ng schedule at follow-ups para sa team.',
    today: 'Schedule ngayon',
    pending: 'Kailangang i-confirm',
    vaccines: 'Vaccines na due',
    recovered: 'Na-recover ng reminders',
    recoveredHelp: 'Confirmed appointments na may na-send na reminder.',
    appointments: 'appointments',
    emptyToday: 'Wala pang appointment ngayon.',
    emptyPending: 'Wala pang pending confirmation.',
    emptyVaccines: 'Wala pang vaccine follow-up na due.',
    walkIns: 'Walk-ins ngayon',
    emptyWalkIns: 'Wala pang walk-in ngayon.',
    qrLink: 'I-print ang walk-in QR',
    completeAction: 'Markahan na complete',
    completed: 'Complete na ang appointment.',
    completeError: 'Hindi ma-markahan ang appointment ngayon.',
    feedback: 'Private feedback',
    emptyFeedback: 'Wala pang private feedback.',
    petCardAction: 'Buksan ang pet card',
    petCardError: 'Hindi mabuksan ang pet card ngayon.',
    analytics: 'Clinic signals',
    noShowRate: 'No-show rate',
    lastSevenDays: 'Huling 7 araw',
    noShowSummary: '{noShows} no-show sa {visits} completed visits',
    busiest: 'Pinaka-busy',
    busiestTime: 'Top time',
    busiestService: 'Top service',
    appointmentsCount: '{count} appointments',
    reminderConversion: 'Reminder to confirm',
    vaccineRecovery: 'Vaccine campaign recovery',
    conversionSummary: '{converted} sa {sent} na-send na reminders',
    recoverySummary: '{recovered} sa {sent} vaccine campaigns',
    noAnalytics: 'Wala pang sapat na data.',
    demoTitle: 'Staff dashboard',
    demoHelp: 'Ilagay ang demo access code para makita ang live clinic desk.',
    demoAction: 'Open dashboard',
    demoError: 'Hindi ma-access ang dashboard. Suriin ang demo code.',
    loading: 'Kinukuha ang live clinic data...',
    bookingLink: 'Mag-book'
    ,revenue: 'Naka-record na paid', outstanding: 'Outstanding records', invoiceAction: 'Gumawa ng invoice', receiptAction: 'Buksan ang receipt', paidAction: 'Markahang paid', unpaidAction: 'Markahang unpaid', invoiceError: 'Hindi ma-update ang invoice ngayon.'
  },
  invoices: { receiptTitle: 'Invoice record', recordLabel: 'Record only — walang payment na kinokolekta dito.', total: 'Total', print: 'I-print', unavailable: 'Hindi available ang receipt na ito.' },
  walkIn: {
    kicker: 'Walk-in check-in',
    title: 'Mag-check in para sa alaga mo.',
    intro: 'Ilagay ang detalye sa ibaba para maihanda ng team ang inyong visit.',
    formTitle: 'Walk-in details',
    ownerName: 'Pangalan ninyo',
    mobile: 'Mobile number',
    petName: 'Pangalan ng alaga',
    species: 'Uri ng alaga',
    speciesOptions: { dog: 'Aso', cat: 'Pusa', other: 'Iba pa' },
    breed: 'Breed (optional)',
    reason: 'Dahilan ng visit',
    submit: 'Mag-check in',
    submitting: 'Sine-save ang check-in...',
    required: 'Pakikumpleto ang required fields.',
    successTitle: 'Nasa queue na ang alaga mo.',
    success: 'Na-save ang inyong check-in. Tatawagin kayo ng clinic team sa lalong madaling panahon.',
    another: 'Mag-check in ng ibang alaga',
    unavailable: 'Hindi ma-save ang check-in ngayon. Subukan ulit mamaya.',
    qrTitle: 'Walk-in QR',
    qrIntro: 'I-print ito at ilagay sa front desk. I-scan para buksan ang mobile check-in form.',
    qrError: 'Hindi magawa ang QR sa address na ito. Gumamit ng mas maikling public domain.',
    print: 'I-print ang QR'
  },
  petCard: {
    tokenDays: 30,
    kicker: 'Pet passport',
    title: 'Health card ni {pet}',
    profile: 'Profile',
    species: 'Uri',
    speciesOptions: { dog: 'Aso', cat: 'Pusa', other: 'Iba pa' },
    breed: 'Breed',
    nextDue: 'Susunod na vaccine',
    noNextDue: 'Wala pang vaccine schedule.',
    vaccines: 'Vaccine history',
    noVaccines: 'Wala pang vaccine history.',
    administered: 'Naibigay',
    due: 'Due',
    visits: 'Past visits',
    noVisits: 'Wala pang past visit.',
    unavailable: 'Hindi na available ang pet card na ito.'
  },
  seed: {
    vet: { id: 'vet-dr-santos', name: 'Dr. Ana Santos', title: 'Veterinarian' },
    owner: { id: 'owner-maria-cruz', name: 'Maria Cruz', mobile: '+639175550001', email: 'maria.cruz@example.test', preferredChannel: 'sms' },
    pet: { id: 'pet-bantay', name: 'Bantay', species: 'dog', breed: 'Aspin' },
    vaccination: { name: '5-in-1', administeredOn: '2025-07-25', dueOn: '2026-07-25' },
    analyticsOwner: { id: 'owner-analytics-ph', name: 'Paolo Reyes', mobile: '+639175550002', email: 'paolo.reyes@example.test', preferredChannel: 'sms' },
    analyticsPets: [
      { id: 'pet-campaign-recovered-ph', name: 'Mochi', species: 'cat', breed: 'Puspin' },
      { id: 'pet-campaign-pending-ph', name: 'Tala', species: 'dog', breed: 'Aspin' }
    ]
  },
  services: [
    { id: 'service-consult', name: 'General Consultation', description: 'Check-up para sa inyong alaga.', durationMinutes: 30, priceCentavos: 65000 },
    { id: 'service-5in1', name: '5-in-1 Vaccination', description: 'Protection against common canine diseases.', durationMinutes: 20, priceCentavos: 90000 },
    { id: 'service-rabies', name: 'Anti-rabies Vaccination', description: 'Annual rabies protection.', durationMinutes: 20, priceCentavos: 55000 },
    { id: 'service-groom', name: 'Basic Grooming', description: 'Bath, nail trim, and ear cleaning.', durationMinutes: 60, priceCentavos: 80000 }
  ],
  hours: [
    { weekday: 1, startsAt: '09:00', endsAt: '17:00', capacity: 1 },
    { weekday: 2, startsAt: '09:00', endsAt: '17:00', capacity: 1 },
    { weekday: 3, startsAt: '09:00', endsAt: '17:00', capacity: 1 },
    { weekday: 4, startsAt: '09:00', endsAt: '17:00', capacity: 1 },
    { weekday: 5, startsAt: '09:00', endsAt: '17:00', capacity: 1 },
    { weekday: 6, startsAt: '09:00', endsAt: '13:00', capacity: 1 }
  ]
};
