export default {
  id: 'clinic-harbour',
  slug: 'harbour-veterinary',
  name: 'Harbour Veterinary',
  locale: 'en-AU',
  timezone: 'Australia/Sydney',
  currency: 'AUD',
  phone: '+61 2 5550 0188',
  email: 'hello@harbourvet.example',
  address: 'Surry Hills, Sydney',
  language: 'english',
  access: {
    bookingTitle: 'Book a visit',
    chatTitle: 'Clinic chat',
    help: 'Enter the demo access code from the clinic team to continue.',
    label: 'Demo access code',
    bookingAction: 'Continue',
    chatAction: 'Continue',
    error: 'We could not access the demo. Check the code and try again.',
    staffTitle: 'Staff dashboard',
    staffHelp: 'Enter the staff access code to view the live clinic desk.',
    staffLabel: 'Staff access code',
    staffAction: 'Open dashboard',
    staffError: 'We could not access the staff dashboard. Check the code and try again.'
  },
  booking: {
    kicker: 'Online appointment',
    headline: 'Thoughtful care, right on time.',
    intro: 'Choose a service and a time that suits you. We confirm every appointment before your visit.',
    accessLabel: 'Demo access code',
    accessHelp: 'Enter the code from the clinic team to view live availability.',
    accessAction: 'Continue',
    serviceHeading: 'What can we help with?',
    serviceHelp: 'Choose a service to see available appointment times.',
    dateLabel: 'Choose a date',
    slotsHeading: 'Available times',
    slotsHelp: 'Availability is live. Your selected time will be held while you complete the booking.',
    detailsHeading: 'A few details',
    ownerName: 'Your name',
    mobile: 'Mobile number',
    email: 'Email address (optional)',
    petName: 'Pet name',
    species: 'Pet type',
    speciesOptions: { dog: 'Dog', cat: 'Cat', other: 'Other' },
    breed: 'Breed (optional)',
    bookAction: 'Confirm appointment',
    booking: 'Saving your appointment...',
    bookedHeading: 'Your visit is booked.',
    bookedBody: 'Your reservation is in place. We will send a confirmation and reminder before the visit.',
    anotherAction: 'Book another visit',
    unavailable: 'That time was just booked. Please choose another available time.',
    slotsEmpty: 'There are no available times on this date. Try another date.',
    loading: 'Checking live availability...',
    timeZoneNote: 'All times are shown in clinic time.',
    required: 'Please complete the required fields.',
    accessError: 'We could not access the demo. Check the code and try again.'
  },
  reminders: {
    confirm: {
      subject: 'Please confirm {pet}’s appointment',
      message: 'Hi {owner}, {pet} has a {service} appointment at {clinic} on {appointmentTime}. Confirm: {confirmUrl} Reschedule: {rescheduleUrl}'
    },
    appointment_24h: {
      subject: 'Reminder: {pet}’s appointment tomorrow',
      message: 'Hi {owner}, a reminder that {pet} has a {service} appointment at {clinic} tomorrow, {appointmentTime}. Confirm: {confirmUrl} Reschedule: {rescheduleUrl}'
    },
    appointment_2h: {
      subject: '{pet}’s appointment is in 2 hours',
      message: 'Hi {owner}, {pet} has a {service} appointment at {clinic} in 2 hours, {appointmentTime}. Confirm: {confirmUrl} Reschedule: {rescheduleUrl}'
    },
    vaccine_due: {
      subject: 'Vaccination reminder for {pet}',
      message: 'Hi {owner}, {pet} is due for a {vaccine} vaccination. Book with {clinic}: {bookingUrl}'
    },
    no_show: {
      subject: 'Missed visit for {pet}',
      message: 'Hi {owner}, it looks like {pet} missed a visit. Reschedule with {clinic}: {rescheduleUrl}'
    },
    ownerActions: {
      confirmTitle: 'Confirm your appointment',
      rescheduleTitle: 'Reschedule your appointment',
      confirmPrompt: 'Select continue to confirm your appointment.',
      reschedulePrompt: 'Select continue to mark your appointment for rescheduling.',
      continueAction: 'Continue',
      confirmed: 'Your appointment is confirmed.',
      alreadyConfirmed: 'Your appointment is already confirmed.',
      rescheduled: 'Your appointment has been marked for rescheduling. Please contact the clinic to choose a new time.',
      unavailable: 'This link is no longer available.'
    }
  },
  reviews: {
    delayHours: 2,
    googleReviewUrl: 'https://www.google.com/search?q=Harbour+Veterinary+Surry+Hills',
    request: {
      subject: 'How was {pet}’s visit?',
      message: 'Hi {owner}, thank you for visiting {clinic}. How is {pet} doing? Please rate your experience here: {reviewUrl}'
    },
    gate: {
      kicker: 'Clinic feedback',
      title: 'How was {pet}’s visit?',
      intro: 'Your feedback helps us care better.',
      prompt: 'How many stars would you give us?',
      starLabel: '{rating} stars',
      feedbackTitle: 'Tell us how we can improve.',
      feedbackLabel: 'Private feedback',
      feedbackAction: 'Send feedback',
      submitting: 'Saving your feedback...',
      thanksTitle: 'Thank you for your feedback.',
      thanks: 'It has been sent to the clinic team.',
      unavailable: 'This review link is unavailable.',
      ratingError: 'We could not save your rating. Please try again.',
      feedbackError: 'We could not save your feedback. Please try again.',
      required: 'Please enter your feedback.'
    }
  },
  faqs: [
    { question: 'What are your hours?', answer: 'We are open Monday to Friday, 9 AM to 5 PM.' },
    { question: 'Where are you located?', answer: 'We are located in Surry Hills, Sydney.' },
    { question: 'Do you accept walk-ins?', answer: 'Appointments are recommended so we can reserve the right time for your pet.' }
  ],
  chat: {
    title: 'Ask the vet team',
    intro: 'Ask about the clinic or book an appointment in this chat.',
    greeting: 'Hello! I am the virtual receptionist for {clinic}. I can answer clinic questions and help book a visit for your pet.',
    inputLabel: 'Message for the clinic',
    inputPlaceholder: 'For example: Do you have an anti-rabies appointment tomorrow?',
    sendAction: 'Send',
    accessError: 'We could not access chat. Check the demo code and try again.',
    unavailable: 'Chat is unavailable right now. Please try again shortly.'
  },
  dashboard: {
    title: 'Clinic desk',
    intro: 'A live view of the schedule and follow-ups for the team.',
    today: 'Today’s schedule',
    pending: 'Needs confirmation',
    vaccines: 'Vaccinations due',
    recovered: 'Recovered by reminders',
    recoveredHelp: 'Confirmed appointments with a sent reminder.',
    appointments: 'appointments',
    emptyToday: 'No appointments today.',
    emptyPending: 'No confirmations are pending.',
    emptyVaccines: 'No vaccination follow-ups are due.',
    walkIns: 'Walk-ins today',
    emptyWalkIns: 'No walk-ins yet today.',
    qrLink: 'Print walk-in QR',
    completeAction: 'Mark complete',
    completed: 'Appointment marked complete.',
    completeError: 'We could not mark this appointment complete.',
    feedback: 'Private feedback',
    emptyFeedback: 'No private feedback yet.',
    petCardAction: 'Open pet card',
    petCardError: 'We could not open the pet card.',
    analytics: 'Clinic signals',
    noShowRate: 'No-show rate',
    lastSevenDays: 'Last 7 days',
    noShowSummary: '{noShows} no-shows from {visits} closed visits',
    busiest: 'Busiest',
    busiestTime: 'Top time',
    busiestService: 'Top service',
    appointmentsCount: '{count} appointments',
    reminderConversion: 'Reminder to confirmation',
    vaccineRecovery: 'Vaccine campaign recovery',
    conversionSummary: '{converted} of {sent} sent reminders',
    recoverySummary: '{recovered} of {sent} vaccine campaigns',
    noAnalytics: 'Not enough data yet.',
    demoTitle: 'Staff dashboard',
    demoHelp: 'Enter the demo access code to view the live clinic desk.',
    demoAction: 'Open dashboard',
    demoError: 'We could not access the dashboard. Check the demo code.',
    loading: 'Loading live clinic data...',
    bookingLink: 'Booking'
    ,revenue: 'Recorded as paid', outstanding: 'Outstanding records', invoiceAction: 'Create invoice', receiptAction: 'Open receipt', paidAction: 'Mark paid', unpaidAction: 'Mark unpaid', invoiceError: 'We could not update the invoice.'
  },
  invoices: { receiptTitle: 'Invoice record', recordLabel: 'Record only — no payment is collected here.', total: 'Total', print: 'Print', unavailable: 'This receipt is unavailable.' },
  walkIn: {
    kicker: 'Walk-in check-in',
    title: 'Check in your pet.',
    intro: 'Share the details below so the clinic team can prepare for your visit.',
    formTitle: 'Walk-in details',
    ownerName: 'Your name',
    mobile: 'Mobile number',
    petName: 'Pet name',
    species: 'Pet type',
    speciesOptions: { dog: 'Dog', cat: 'Cat', other: 'Other' },
    breed: 'Breed (optional)',
    reason: 'Reason for visit',
    submit: 'Check in',
    submitting: 'Saving your check-in...',
    required: 'Please complete the required fields.',
    successTitle: 'Your pet is in the queue.',
    success: 'Your check-in has been saved. The clinic team will call you as soon as possible.',
    another: 'Check in another pet',
    unavailable: 'We could not save your check-in. Please try again shortly.',
    qrTitle: 'Walk-in QR',
    qrIntro: 'Print this for the front desk. Scan it to open the mobile check-in form.',
    qrError: 'We could not create a QR code for this address. Use a shorter public domain.',
    print: 'Print QR'
  },
  petCard: {
    tokenDays: 30,
    kicker: 'Pet passport',
    title: '{pet}’s health card',
    profile: 'Profile',
    species: 'Type',
    speciesOptions: { dog: 'Dog', cat: 'Cat', other: 'Other' },
    breed: 'Breed',
    nextDue: 'Next vaccination',
    noNextDue: 'No vaccination is scheduled.',
    vaccines: 'Vaccination history',
    noVaccines: 'No vaccination history yet.',
    administered: 'Given',
    due: 'Due',
    visits: 'Past visits',
    noVisits: 'No past visits yet.',
    unavailable: 'This pet card is unavailable.'
  },
  seed: {
    vet: { id: 'vet-dr-reid', name: 'Dr. Charlotte Reid', title: 'Veterinarian' },
    owner: { id: 'owner-amelia-harris', name: 'Amelia Harris', mobile: '+61412345678', email: 'amelia.harris@example.test', preferredChannel: 'sms' },
    pet: { id: 'pet-scout', name: 'Scout', species: 'dog', breed: 'Australian Kelpie' },
    vaccination: { name: 'C5', administeredOn: '2025-07-25', dueOn: '2026-07-25' },
    analyticsOwner: { id: 'owner-analytics-western', name: 'Elliot Jones', mobile: '+61412345679', email: 'elliot.jones@example.test', preferredChannel: 'sms' },
    analyticsPets: [
      { id: 'pet-campaign-recovered-western', name: 'Poppy', species: 'cat', breed: 'Domestic Shorthair' },
      { id: 'pet-campaign-pending-western', name: 'Milo', species: 'dog', breed: 'Cavoodle' }
    ]
  },
  services: [
    { id: 'service-consult', name: 'General Consultation', description: 'A check-up for your pet.', durationMinutes: 30, priceCentavos: 8500 },
    { id: 'service-5in1', name: 'Canine Vaccination', description: 'Routine canine vaccination.', durationMinutes: 20, priceCentavos: 11000 },
    { id: 'service-rabies', name: 'Rabies Vaccination', description: 'Rabies protection where required.', durationMinutes: 20, priceCentavos: 7500 },
    { id: 'service-groom', name: 'Basic Grooming', description: 'Bath, nail trim, and ear cleaning.', durationMinutes: 60, priceCentavos: 9500 }
  ],
  hours: [
    { weekday: 1, startsAt: '09:00', endsAt: '17:00', capacity: 1 },
    { weekday: 2, startsAt: '09:00', endsAt: '17:00', capacity: 1 },
    { weekday: 3, startsAt: '09:00', endsAt: '17:00', capacity: 1 },
    { weekday: 4, startsAt: '09:00', endsAt: '17:00', capacity: 1 },
    { weekday: 5, startsAt: '09:00', endsAt: '17:00', capacity: 1 }
  ]
};
